---
- name: Create pods using deployment 
  hosts: master-node
  become: true

 
  tasks: 
  - name: create a deployment
    command: kubectl apply -f deployment.yml
 
  - name: update deployment with new pods if image updated in docker hub
    command: kubectl rollout restart deployment capstone-deployment
