---
- hosts: master-node
  become: true

  tasks:
  - name: create docker image using dockerfile file
    command: docker build -t capstone:latest .

  - name: create tag to image
    command: docker tag capstone rajas2716/capstone

  - name: push image on to dockerhub
    command: docker push rajas2716/capstone


