apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  labels:
    app: capstone-project
spec:
  selector:
    app: capstone-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31200
